let idCounter = 0;

export const ITEMS = [
  {
    id: String(idCounter++),
    imageSrc: "../assets/car.png",
    title: "Kids Electric Car",
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: "Gaming",
    details:
      "An exciting electric car for kids to drive around in style, providing hours of entertainment and fun.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/camera.png",
    title: "CANON EOS DSLR Camera",
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: "Technology",
    details:
      "Capture stunning photos and videos with this professional-grade Canon DSLR camera, perfect for photography enthusiasts.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/dogfood.png",
    price: 100,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: "Breed Dry Dog Food",
    type: "General",
    details:
      "Nutritious dry dog food to keep your furry friend healthy and happy, made with high-quality ingredients.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/labtop.png",
    price: 700,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: "ASUS FHD Gaming Laptop",
    type: "Technology",
    details:
      "A complete skincare set by Curology to cleanse, moisturize, and protect your skin, leaving it soft and radiant.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/cream.png",
    price: 500,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: "Curology Product Set",
    type: "General",
    details:
      "Enhance your gaming experience with the GP11 Shooter USB gamepad, featuring high-quality construction and precise controls.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/g-black.png",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "GP11 Shooter USB Gamepad",
    type: "Gaming",
    details:
      "Enhance your gaming experience with the GP11 Shooter USB gamepad, featuring high-quality construction and precise controls.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/jacket.png",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "Quilted Satin Jacket",
    type: "Clothes",
    details:
      "Stay stylish and warm with this quilted satin jacket, perfect for adding a trendy touch to your outfit.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/bookself.png",
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "Small Bookshelf",
    type: "General",
    details:
      "Organize your books and decorative items neatly with this small bookshelf, designed to fit in compact spaces.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/headphones.png",
    price: 160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "RGB Liquid CPU Cooler",
    type: "Technology",
    details:
      "Keep your CPU cool and running smoothly with the RGB liquid CPU cooler, featuring a high-performance pump and customizable RGB lighting.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/bag.png",
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "Gucci Duffle Bag",
    type: "Clothes",
    details:
      "Travel in style with the Gucci duffle bag, crafted from premium materials and designed for durability and luxury.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/coat.png",
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "The North Coat",
    type: "Clothes",
    details:
      "Stay warm and fashionable with The North Coat, featuring a durable construction and timeless design.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/g-colored.png",
    price: 160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: "HAVIT HV-G92 Gamepad",
    type: "Gaming",
    details:
      "Enjoy responsive and precise gaming controls with the HAVIT HV-G92 gamepad, designed for hours of gaming fun.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/keyboard.png",
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 35,
    quantity: 0,
    title: "AK-900 Wired Keyboard",
    type: "Technology",
    details:
      "Immerse yourself in gaming with the IPS LCD gaming monitor, delivering vibrant visuals and smooth gameplay.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/tv.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 30,
    quantity: 0,
    title: "IPS LCD Gaming Monitor",
    type: "Technology",
    details:
      "Immerse yourself in gaming with the IPS LCD gaming monitor, delivering vibrant visuals and smooth gameplay.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/chair.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 25,
    quantity: 0,
    title: "S-Series Comfort Chair",
    type: "Clothes",
    details:
      "Relax in comfort with the S-Series comfort chair, featuring ergonomic design and plush cushioning for long hours of sitting.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/JBL_BOOMBOX.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "JBL Boombox 2",
    type: "New Arrival",
    details:
      "Experience powerful sound with the JBL Boombox 2, featuring a rugged design and long battery life for all-day listening.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/perfume.png",

    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "perfume",
    type: "New Arrival",
    details:
      "This perfume is a blend of oud, rose, and incense, creating a rich and luxurious scent that lasts all day.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/phone.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "Phone",
    type: "New Arrival",
    details:
      "This phone features a large display, powerful processor, and long battery life, perfect for work and play.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/playstation.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "PlayStation 5",
    type: "New Arrival",
    details: "The black and white version of the PS5 is coming out on sale.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/speakers.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "Speaker",
    type: "New Arrival",
    details: "Amazing sound quality with the Amazon wireless speaker.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/womenCollections.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "Women's Collections",
    type: "New Arrival",
    details:
      "Women's collections are featured that give you another vibe, and you can find the best collections here.",
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/shoes.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: "Football Shoes",
    type: "New Arrival",
    details:
      "The best football shoes for your game, and you can find the best collections here.",
  },
];
